# Generated by Django 5.0.6 on 2024-06-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_icon', models.CharField(max_length=50)),
                ('info_text', models.TextField()),
            ],
        ),
    ]
